#### 一、无论成功还是失败都执行的操作

* ```javascript
  const Gen = (time) => {
      return new Promise((resolve, reject) => {
          setTimeout(function () {
              if (time < 500) {
                  reject(time)
              } else {
                  resolve(time)
              }
          }, time)
      })
  }
  Gen(Math.random() * 1000)
      .then(val => console.log('resolve', val))
      .catch(err => console.log('reject', err))
      .finally(() => console.log('finally'))//无论成功还是失败都可以有的操作
  ```

  